name = "Create modpack"
author = "Piecuu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15c9f1b1209bd74f1de7cea7ae1e4b126afb7af3fe8af2d229dcb991578f39ea"

[versions]
fabric = "0.16.2"
minecraft = "1.20.1"
