name = "Create modpack"
author = "Piecuu"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4c62f952c00628f9f4cad1d58d4e1edea09fe530006233c7bd39206ec574f31"

[versions]
fabric = "0.16.2"
minecraft = "1.20.1"
