name = "Create modpack"
author = "Piecuu"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6df52ebea7befcf6ef07f22bc923f7b8a80536982227f9a24e2bf058c298086"

[versions]
fabric = "0.16.2"
minecraft = "1.20.1"
