name = "Create modpack"
author = "Piecuu"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "348d4332ae00a35953639892eb051020d1949b70081bca73f010ae7d68c64432"

[versions]
fabric = "0.16.2"
minecraft = "1.20.1"
